[project]
name = "upstage-infra-project"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "cryptography>=46.0.3",
    "pymysql>=1.1.2",
    "sqlalchemy>=2.0.44",
    "python-dotenv>=1.2.1",
]
